apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: contacts-web-app
  ports:
    - protocol: TCP
      port: 5001        
      targetPort: 5000