apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: contacts-db-mysql
        image: pintop9/contacts-db-mysql  
        env:
        - name: MYSQL_DATABASE
          value: "contacts_db"
        - name: MYSQL_USER
          value: "contacts_user"
        - name: MYSQL_PASSWORD
          value: "contacts_pass"
        - name: MYSQL_ROOT_PASSWORD
          value: "contacts_pass"
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-database-service
spec:
  selector: 
    app: mysql-db
  ports:
  - protocol: TCP  
    port: 3306
    targetPort: 3306 
  type: ClusterIP 