apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-db
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mssql-db
  template:
    metadata:
      labels:
        app: mssql-db
    spec:
      containers:
      - name: contacts-db-mssql
        image: pintop9/contacts-db-mssql  
        env:
        - name: MSSQL_DATABASE
          value: "contacts_db"
        - name: SA_PASSWORD
          value: "Y9&ZvR4*2?BdNp"
        - name: ACCEPT_EULA
          value: "Y"
        ports:
        - containerPort: 1433

---
apiVersion: v1
kind: Service
metadata:
  name: mssql-database-service
spec:
  selector: 
    app: mssql-db
  ports:
  - protocol: TCP  
    port: 1433
    targetPort: 1433 
  type: ClusterIP 