apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: contacts-db-postgres
        image: pintop9/contacts-db  
        env:
        - name: POSTGRES_DB
          value: "contacts_db"
        - name: POSTGRES_USER
          value: "contacts_user"
        - name: POSTGRES_PASSWORD
          value: "contacts_pass"
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: my-database-service
spec:
  selector: 
    app: postgres-db
  ports:
  - protocol: TCP  # Protocol
    port: 5432
    targetPort: 5432 
  type: ClusterIP 